name: pylint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip3 install pylint
        pip3 install -r requirements.txt
        pip3 install -r requirements_bpreport.txt
    - name: Analysing the code with pylint and Google's pylintrc
      run: |
        set -o pipefail
        pylint --rcfile .github/workflows/pylintrc --fail-under=10 `find -regextype egrep -regex '(.*.py)$'` | tee pylint.txt
        ls
        cat pylint.txt
    - name: Upload pylint.txt as artifact
      uses: actions/upload-artifact@v4
      with:
        name: pylint report
        path: pylint.txt
